name:                top
version:             0.1.0.0
github:              "ldr709/top"
license:             BSD3
author:              "Lance Roy"
maintainer:          "ldr709@gmail.com"
copyright:           "2018 Lance Roy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ldr709/top#readme>

dependencies:
- base >= 4.7 && < 5
- streams
- transformers
- unamb

library:
  source-dirs: src

tests:
  top-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - top
